### ISSUE TITLE
Test failure on Windows

### ISSUE THREAD

**Issue by FlorianStasse** [specta-rs/tauri-specta#132]
I have a Tauri app that uses Tauri Specta to generate bindings for my plugins. On Linux and MacOS everything works fine.

But on Windows I cannot generate the bindings as it fails with the following error:

(exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)

To be sure that I have an issue with this lib, I cloned the repo and ran the tests, but it failed with the same error (I also tried to run the tests on another Windows machine, and it also failed).

I'm pretty sure it's not an issue with Tauri Specta itself, but I have no clue how to fix this kind of error.

Any help is welcomed !

**Comment by oscartbeaumont** [comment]
I would be incredibly surprised if this was Tauri Specta as we don't touch any native stuff (and don't do stuff differently across OS's). I think you might want to report this problem to [Tauri](https://github.com/tauri-apps/tauri).

**Comment by FlorianStasse** [comment]
The strange thing is that Tauri itself is fine, I can run the main application (obviously it will raise some errors when I try to use the bindings that were not exported).
That's why I thought about creating an issue here. I'll try to get help on the Tauri discord.

**Comment by oscartbeaumont** [comment]
Give the latest Tauri/Tauri Specta version a go. It's possible it will fix this.
