### ISSUE TITLE
How to use channels?

### ISSUE THREAD

**Issue by Somfic** [specta-rs/tauri-specta#146]
A bit confused on how to use channels with `tauri-specta`, as there is no documentation

**Comment by oscartbeaumont** [comment]
I'm fairly sure it just works the same as with regular Tauri ([docs](https://v2.tauri.app/develop/calling-frontend/#channels)). Are you running into any errors or anything?

**Comment by Somfic** [comment]
Sorry, my `T` type in `Channel<T>` did not correctly implement `specta::Type`, making me think the issue was with the `Channel`. Works at intended after correctly implementing `specta::Type` 😅
