### ISSUE TITLE
Move the repo

### ISSUE THREAD

**Issue by oscartbeaumont** [specta-rs/tauri-specta#50]
There was interest early on in moving this repo into the Tauri org. It's a thin wrapper to tie Specta and Tauri so I think honestly that would be great. No pressure on the Tauri side if they have changed their mind.

Launching the next major version of tauri-specta is currently blocked on Specta v2 and Tauri v2 coming out. I am estimating Feb next year for Specta v2 to launch but we will see. I assume this would be a good time to move the repo as telling people to use beta releases isn't great for stability.

If not we will move this repo to the `specta-rs` org.

**Comment by silvermind20** [comment]
Any update on this?

**Comment by oscartbeaumont** [comment]
Have moved to `specta-rs`.
